// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    using System;

    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(4)
            {
                { typeof(global::System.Collections.Generic.List<global::Game.Map.MapEdgeData>), 0 },
                { typeof(global::Game.Map.EdgeTypes), 1 },
                { typeof(global::Game.Map.Map), 2 },
                { typeof(global::Game.Map.MapEdgeData), 3 },
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ListFormatter<global::Game.Map.MapEdgeData>();
                case 1: return new MessagePack.Formatters.Game.Map.EdgeTypesFormatter();
                case 2: return new MessagePack.Formatters.Game.Map.MapFormatter();
                case 3: return new MessagePack.Formatters.Game.Map.MapEdgeDataFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1649 // File name should match first type name


// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Game.Map
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class EdgeTypesFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Game.Map.EdgeTypes>
    {
        public void Serialize(ref MessagePackWriter writer, global::Game.Map.EdgeTypes value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.Write((Int32)value);
        }

        public global::Game.Map.EdgeTypes Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            return (global::Game.Map.EdgeTypes)reader.ReadInt32();
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name



// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Game.Map
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class MapFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Game.Map.Map>
    {

        public void Serialize(ref MessagePackWriter writer, global::Game.Map.Map value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            writer.Write(value.R);
            writer.Write(value.C);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<global::Game.Map.MapEdgeData>>().Serialize(ref writer, value.Edges, options);
        }

        public global::Game.Map.Map Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __R__ = default(int);
            var __C__ = default(int);
            var __Edges__ = default(global::System.Collections.Generic.List<global::Game.Map.MapEdgeData>);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __R__ = reader.ReadInt32();
                        break;
                    case 1:
                        __C__ = reader.ReadInt32();
                        break;
                    case 2:
                        __Edges__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<global::Game.Map.MapEdgeData>>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Game.Map.Map();
            ____result.R = __R__;
            ____result.C = __C__;
            ____result.Edges = __Edges__;
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class MapEdgeDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Game.Map.MapEdgeData>
    {

        public void Serialize(ref MessagePackWriter writer, global::Game.Map.MapEdgeData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(7);
            writer.Write(value.R);
            writer.Write(value.C);
            writer.Write(value.Rotation);
            formatterResolver.GetFormatterWithVerify<global::Game.Map.EdgeTypes>().Serialize(ref writer, value.EdgeType, options);
            formatterResolver.GetFormatterWithVerify<float?>().Serialize(ref writer, value.Voltage, options);
            formatterResolver.GetFormatterWithVerify<float?>().Serialize(ref writer, value.Resistance, options);
            formatterResolver.GetFormatterWithVerify<float?>().Serialize(ref writer, value.MaxCurrent, options);
        }

        public global::Game.Map.MapEdgeData Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __R__ = default(ushort);
            var __C__ = default(ushort);
            var __Rotation__ = default(short);
            var __EdgeType__ = default(global::Game.Map.EdgeTypes);
            var __Voltage__ = default(float?);
            var __Resistance__ = default(float?);
            var __MaxCurrent__ = default(float?);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __R__ = reader.ReadUInt16();
                        break;
                    case 1:
                        __C__ = reader.ReadUInt16();
                        break;
                    case 2:
                        __Rotation__ = reader.ReadInt16();
                        break;
                    case 3:
                        __EdgeType__ = formatterResolver.GetFormatterWithVerify<global::Game.Map.EdgeTypes>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __Voltage__ = formatterResolver.GetFormatterWithVerify<float?>().Deserialize(ref reader, options);
                        break;
                    case 5:
                        __Resistance__ = formatterResolver.GetFormatterWithVerify<float?>().Deserialize(ref reader, options);
                        break;
                    case 6:
                        __MaxCurrent__ = formatterResolver.GetFormatterWithVerify<float?>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Game.Map.MapEdgeData();
            ____result.R = __R__;
            ____result.C = __C__;
            ____result.Rotation = __Rotation__;
            ____result.EdgeType = __EdgeType__;
            ____result.Voltage = __Voltage__;
            ____result.Resistance = __Resistance__;
            ____result.MaxCurrent = __MaxCurrent__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

